# Test against this version of node.js
environment:
  matrix:
  - nodejs_version: "6"
# Install scripts. (runs after repo clonin)
install:
# Get the lates stable version of Node.js or io.js
  - ps: install-product node $env:nodejs_version
  # Install modules
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off